### ISSUE TITLE
prismacloud_integration now broken

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/terraform-provider-prismacloud#113]
## Describe the bug

Previously working `prismacloud_integration` resources are now throwing errors.

## Expected behavior

`prismacloud_integration` resource should create an integration.

## Current behavior

Getting an unexpected end of JSON input
```
│ Error: unexpected end of JSON input
│ 
│   with prismacloud_integration.integration_sqs,
│   on integrations.tf line 1, in resource "prismacloud_integration" "integration_sqs":
│    1: resource "prismacloud_integration" "integration_sqs" {
```

## Steps to reproduce

1. Define a "prismacloud_integration"
2. Add an integration_config {}
3. Try to `terraform plan`
4. See `Error: unexpected end of JSON input`

## Context

**This has broken our ability to manage our Prisma Cloud instance right now.**

Integration Terraform
```
resource "prismacloud_integration" "integration_sqs" {
  name             = "integration_sqs"
  integration_type = "amazon_sqs"
  description      = "SQS for integration"
  enabled          = true
  integration_config {
    queue_url = "sample queue"
  }
}
```

## Your Environment

- Version used:
prismacloud 1.2.2
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by netjordan** [comment]
I can confirm we're also having this issue. I think it might be related to a change in Prisma Cloud rather than this provider specifically. We had the issue with both 1.1.10 and 1.2.2 of this provider.

Looking at the release notes, there's some deprecated intergration endpoints - https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-release-notes/prisma-cloud-release-information/features-introduced-in-2022/features-introduced-in-january-2022.html 

Could this be related?

**Comment by daemienb** [comment]
I can confirm we're also having this issue, could this please be looked at asap
