### ISSUE TITLE
Terraform plan stage "Client.Timeout exceeded while awaiting headers" error

### ISSUE THREAD

**Issue by iokush** [PaloAltoNetworks/terraform-provider-prismacloud#133]
## Describe the bug

Lately, we've been getting _Client.Timeout exceeded while awaiting headers_ error when running terraform plan which involves creating policies and saved searches. Sometimes retrying the stage works but not always.

## Current behavior

Example error message: 
│ Error: Post "https://api.eu.prismacloud.io/search/config": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│   on policy/main.tf line 28, in resource "prismacloud_rql_search" "this":
│   28: resource "prismacloud_rql_search" "this" {

## Your Environment

Version used: Terraform v1.0.11, paloaltonetworks/prismacloud v1.2.6

**Comment by iokush** [comment]
We're seeing the Client.timeout along with a bunch of other errors lately. Our observation is this happens when there are substantial changes to policies, for example adding a tag or updating remediation steps in bulk but these errors are currently blocking us with the rollout.

`Error: 500/https://api.eu.prismacloud.io/search/event Error(msg:internal_error severity:error subject:could not execute search: CannotSerializeTransactionException)`

**Comment by tumbone** [comment]
I have also come across this issue. My observation is that it is being caused by the more complex search queries (rql with joins etc). My wild assumption is that the resource waits for the search results to be returned before creation and that seems to be what results in a timeout.
My current workaround is to delete any of my custom policies that have complex queries and this seems to do the trick for now. I'm hoping there is a way for this to be resolved so I can avoid having to come up with simpler queries.

**Comment by iokush** [comment]
@tumbone That could be the case, for us even simple out of the box search queries show this error so it looks some rate limiting on Prisma Cloud side which fails any subsequent search queries that follow say a complex one which indeed defeats the purpose of the product. We have escalated this issue so hopefully, it can be resolved soon.

**Comment by tumbone** [comment]
@iokush Totally agreed, it definitely defeats the purpose hence I'm hoping avoiding the complex search queries is only a temporary workaround. You are also onto something regarding the rate limiting, you may want to check with Prisma Cloud that they are not running your cluster with scaled down resources.
To add a bit more context here: I've come across a scenario in which I got this timeout when working late into the evening but then performing exactly the same infrastructure update ("terraform apply") worked perfectly fine the next morning.

**Comment by iokush** [comment]
@tumbone We're in touch with them but they don't seem to have identified any rate limiting for our tenant (yet). That's very relatable, we also run into issues where the pipeline works after a while like yours so we didn't mind the error back then but recently the frequency of these timeout errors have increased substantially blocking us for weeks.
Let's hope they find a solution to this altogether but it's good to know there are other impacted customers as well.

**Comment by mtobias-getty** [comment]
Also experiencing this, I believe I have confirmation that this is tied to how the RQL searches are processed, since Terraform is a layer on top of the API, there isn't actually an API for returning RQL search criteria, so they are using the API for returning actual RQL results, which means the searches actually have to run.

I've been told a workaround is to include RQL directly in the policy resource in the criteria section, this doesn't work for me as I want my teams to have the ability to actually run saved searches.  My support ticket is still with engineering escalation.  Currently running 1.2.7 of the provider.  My solution so far is to keep rerunning the pipeline when that error shows up until it succeeds.  :-|

**Comment by trishala1999** [comment]
@iokush @tumbone @mtobias-getty As a workaround can you please try increasing the timeout of TF provider by setting `timeout` parameter in provider block https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs#timeout. Its default value is 90s, so you can try increasing it upto 300-500s because RQL queries can take longer that 5 mins also sometimes. Please try this and let us know if it works for you.

**Comment by mtobias-getty** [comment]
Thank you for the suggestion @trishala1999, this does appear to be a workaround for this issue.  The core issue still exists as even validating many RQL searches can take substantial time.  I've created the following AHA Idea to address what I believe is the core of the issue and would suggest anyone else having this issue also take a look and vote for this https://prismacloud.ideas.aha.io/ideas/PANW-I-4039

**Comment by trishala1999** [comment]
@iokush @tumbone @mtobias-getty In version v1.2.10 we have added support for  a new param `skip_result` in resource [prismacloud_rql_search](https://registry.terraform.io/providers/PaloAltoNetworks/prismacloud/latest/docs/resources/rql_search). Adding this field in RQL search resource block with value as `true` will skip the RQL query execution and search results in response. This should fix the issue.

**Comment by tumbone** [comment]
Hi @trishala1999 Thanks for keeping us in the loop regarding this issue. I have indeed tested this new parameter and I can confirm it does indeed work for us. The custom policies are created a lot quicker than what we had become accustomed to, so this  does seem to resolve the issue in relation to policy creation. Much appreciated!
